---
ConnectionStrings:
#  Elasticsearch: server=http://localhost:9200
#  Cache: provider=redis;server="localhost,abortConnect=false"
#  MessageBus: provider=redis;server="localhost,abortConnect=false"
#  Queue: provider=redis;server="localhost,abortConnect=false"
#  Storage: ''
#  Email: 'smtps://user:password@domain.com:587'
#  LDAP: ''
  OAuth: FacebookId=395178683904310;GitHubId=7ef1dd5bfbc4ccf7f5ef;GoogleId=809763155066-enkkdmt4ierc33q9cft9nf5d5c02h30q.apps.googleusercontent.com;MicrosoftId=000000004C137E8B; AADAppId=29d1a9be--c2f9631141c9; AADAppSecret=wIZ8Q~jyc~-nu3heaDYtRRedtm; SlackId=34500115540.177239122322;
  Hcp:
    ClientId: 6eXwtHXrLDrdFnv
    ClientSecret: dk027PWND-7Gi3gk0rudggubk-0Ge9JYjGo8
    OrgId: 3baadc3797fb
    ProjectId: 4dbc-9ce6-6d8ebf9699f2
    AppName: SyncfusionSupport
    SecretName: syncfusion_dev_ses

# Base url for the ui used to build links in emails and other places.
BaseURL: https://be.exceptionless.io

# Controls whether users can signup.
EnableAccountCreation: true

# Exceptionless Client Settings
ExceptionlessServerUrl: https://collector.exceptionless.io
InternalProjectId: 50ca6b2423d6c8493020b823

Serilog:
  MinimumLevel:
    Default: Warning
  WriteTo:
  - Name: Console
    Args:
      theme: "Serilog.Sinks.SystemConsole.Themes.ConsoleTheme::None, Serilog.Sinks.Console"

Apm:
  ServiceEnvironment: prod
